config/routes.rb
Truedine::Application.routes.draw do
  

  

  match '/search', to: 'search_results#index'
  match '/works' , to: 'static_pages#how_it_works'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  devise_for :users
  resources :users
  get "static_pages/home"

  get "static_pages/restaurants"

  root :to => 'static_pages#home'

  resources :restaurants do
    resources :reservations
  end
  resources :cuisines
  resources :locations
  resources :areas
  

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :first_name, :last_name, :email, :mobile, :password, :password_confirmation, :remember_me
  before_create :assign_role
  # attr_accessible :title, :body
  validates_presence_of :first_name, :last_name
  validates_presence_of :mobile, length: {minimum: 10}

  def assign_role
   # assign a default role if no role is assigned
    self.add_role :user if self.roles.first.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
    <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>
      </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.first_name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <div class="content span4">
   <h4>Enter New Restaurant Information</h4>
   <%= link_to "New Restaurant", new_restaurant_path %>
    <h4>Enter New Cuisine</h4>
    <%= link_to "New Cuisine", new_cuisine_path %>
    <h4>Enter New City/Location</h4>
    <%= link_to "City/Location", new_location_path %>
    <h4>Enter New Area</h4>
    <%= link_to "Area", new_area_path %>
   </div>

</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.first_name %></p>
<p>Email: <%= @user.email if @user.email %></p>