config/routes.rb
Truedine::Application.routes.draw do
  

  

  match '/search', to: 'search_results#index'
  match '/works' , to: 'static_pages#how_it_works'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  devise_for :users
  resources :users
  get "static_pages/home"

  get "static_pages/restaurants"

  root :to => 'static_pages#home'

  resources :restaurants do
    resources :reservations
  end
  resources :cuisines
  resources :locations
  resources :areas
  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible  :description, :menu, :restaurant_name, :area_id
  attr_accessible :cuisine_ids
  attr_accessible :filepicker_url
  belongs_to :area
  has_and_belongs_to_many :cuisines
  has_many :reservations

  include PgSearch
  pg_search_scope :search, against: [:restaurant_name, :description],
    using: {tsearch: {dictionary: "english"} },
    associated_against: {cuisines: :cuisine_name}

  def self.text_search(query)
  	if query.present?
      search(query)
  	  #where("restaurant_name @@ :q or description @@ :q", q: query)
  		
  	else
  	  scoped	
  	end
  	
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
    @locations = Location.all
  end

  def create
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@restaurant = Restaurant.new(params[:restaurant])
  	if @restaurant.save
  	  redirect_to @restaurant, :notice => "Restaurant added"
  	else
  	  render :new
  	end
  	
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
    @locations = Location.all
  	
  end
  def update
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      # Handle a successful update.
      redirect_to @restaurant, :notice => "Restaurant successfully updated"
    else
      render 'edit'
    end
  end
  def destroy
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.destroy
    redirect_to restaurants_path, :notice => "Restaurant deleted."

  	
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<div class="content center">
<h3>Edit Restaurant Information</h3>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :restaurant_name %>
  <%= f.input :description %>
  <%= f.input :menu %>
  <%= f.association :cuisines, label_method: :cuisine_name, value_method: :id %>
 <%= f.input :area_id,collection: @locations, as: :grouped_select, group_method: :areas, label_method: :area_name%>

  <%= f.button :submit %>
<% end %>
</div>

app/views/restaurants/index.html.erb
<%@restaurants.each do |restaurant|%>
  
<div class="content">
 <div class="row">
   <div class="span2">
    <!--<img class="img-polaroid"src="http://placehold.it/146x104" alt="">-->
    <%=filepicker_image_tag restaurant.filepicker_url, w: 146, h: 104, fit: 'clip'%>

  </div>
  <div class="span4">
   <h4> <%= link_to restaurant.restaurant_name, restaurant %></h4>
   <p><%=restaurant.description%></p>
   <%restaurant.cuisines.each do |cuisine|%>
   <p>cuisine: <%=cuisine.cuisine_name%></p>
   <%end%>
   </div>
 </div>
</div>

<%end%>

app/views/restaurants/new.html.erb
<div class="content center">

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :restaurant_name %>
  <%= f.input :description %>
  <%= f.input :menu %>
  <%= f.association :cuisines, label_method: :cuisine_name %>
 <%= f.input :area_id,collection: @locations, as: :grouped_select, group_method: :areas, label_method: :area_name%>
  <div>
    <%= f.label :filepicker_url, "Upload Restaurant Image" %>
    <%= f.filepicker_field :filepicker_url %> <!-- User#filepicker_url is a regular string column -->
  </div>
  
  <%= f.button :submit %>
<% end %>

</div>

app/views/restaurants/show.html.erb
<div class="content">
 <div class="row">
   <div class="span3">
    <!--<img class="img-polaroid"src="http://placehold.it/480x300" alt="">-->
    <%=filepicker_image_tag @restaurant.filepicker_url, w: 480, h: 300, fit: 'clip'%>

  </div>
  <div class="span6">
   <h3> <%= @restaurant.restaurant_name %></h3>
   <p><%=@restaurant.area.area_name%></p>
   <p><%=@restaurant.description%></p>
   <%@restaurant.cuisines.each do |cuisine|%>
   <p>cuisine: <%=cuisine.cuisine_name%></p>
   <%end%>
   
    <!--<%=link_to 'BOOK', new_restaurant_reservation_path(@restaurant),:class => "btn btn-large btn-primary"%>-->
   
   </div>
 </div>
</div>