config/routes.rb
Truedine::Application.routes.draw do
  

  

  match '/search', to: 'search_results#index'
  match '/works' , to: 'static_pages#how_it_works'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  devise_for :users
  resources :users
  get "static_pages/home"

  get "static_pages/restaurants"

  root :to => 'static_pages#home'

  resources :restaurants do
    resources :reservations
  end
  resources :cuisines
  resources :locations
  resources :areas
  

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :location_name
  has_many :areas
  has_many :restaurants, through: :areas
  validates_uniqueness_of :location_name, :case_sensitive => :false
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  	@locations = Location.all
  end

  def new
  	@location = Location.new
  end

  def edit
  	@location = Location.find(params[:id])
  end

  def show
    @location = Location.find(params[:id])
  end

  def create
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@location = Location.new(params[:location])
  	if @location.save
  	  redirect_to @location, :notice => "Location added"
  	else
  	  render :new
  	end
  	
  end

  def update
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      # Handle a successful update.
      redirect_to @location, :notice => "Location successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@location = Location.find(params[:id])
  	@location.destroy
    redirect_to locations_path, :notice => "Location deleted."

  	
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<div class="content">
<h3>Edit Location</h3>
<%= simple_form_for @location do |f| %>
  <%= f.input :location_name %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/locations/index.html.erb
<%@locations.each do |location|%>
<div class="content">
<h4> <%= link_to location.location_name, location %></h4>
<%= link_to("Delete Location", location_path(location), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
</div>
<%end%>

app/views/locations/new.html.erb
<div class="content">
<%= simple_form_for @location do |f| %>
  <%= f.input :location_name %>
  <%= f.button :submit %>
<% end %>
<%=link_to "Locations",locations_path%>
</div>

app/views/locations/show.html.erb
<h3>Location</h3>
<p>City: <%= @location.location_name %></p>
<h4>Areas</h4>
<%@location.areas.each do |area|%>
   <p> <%=link_to area.area_name, area%></p>
<%end%>