config/routes.rb
Truedine::Application.routes.draw do
  

  

  match '/search', to: 'search_results#index'
  match '/works' , to: 'static_pages#how_it_works'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  devise_for :users
  resources :users
  get "static_pages/home"

  get "static_pages/restaurants"

  root :to => 'static_pages#home'

  resources :restaurants do
    resources :reservations
  end
  resources :cuisines
  resources :locations
  resources :areas
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :area_name, :location_id
  belongs_to :location
  has_many :restaurants
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  attr_accessible :cuisine_name
  has_and_belongs_to_many :restaurants
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :location_name
  has_many :areas
  has_many :restaurants, through: :areas
  validates_uniqueness_of :location_name, :case_sensitive => :false
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :day, :number_of_people, :special_requirements, :time, :restaurant_id
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible  :description, :menu, :restaurant_name, :area_id
  attr_accessible :cuisine_ids
  attr_accessible :filepicker_url
  belongs_to :area
  has_and_belongs_to_many :cuisines
  has_many :reservations

  include PgSearch
  pg_search_scope :search, against: [:restaurant_name, :description],
    using: {tsearch: {dictionary: "english"} },
    associated_against: {cuisines: :cuisine_name}

  def self.text_search(query)
  	if query.present?
      search(query)
  	  #where("restaurant_name @@ :q or description @@ :q", q: query)
  		
  	else
  	  scoped	
  	end
  	
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :first_name, :last_name, :email, :mobile, :password, :password_confirmation, :remember_me
  before_create :assign_role
  # attr_accessible :title, :body
  validates_presence_of :first_name, :last_name
  validates_presence_of :mobile, length: {minimum: 10}

  def assign_role
   # assign a default role if no role is assigned
    self.add_role :user if self.roles.first.nil?
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
  	@areas= Area.all
  end

  def new
  	@area = Area.new
  end

  def edit
  	@area =Area.find(params[:id])
  end

  def show
  	@area = Area.find(params[:id])
  end

  def create
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@area = Area.new(params[:area])
  	if @area.save
  	  redirect_to @area, :notice => "Area added"
  	else
  	  render :new
  	end
  	
  end

  def update
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@area = Area.find(params[:id])
    if @area.update_attributes(params[:area])
      # Handle a successful update.
      redirect_to @area, :notice => "Area successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
  	authorize! :index, @user, :message => 'Not authorized as an administrator.'
  	@area = Area.find(params[:id])
  	@area.destroy
    redirect_to areas_path, :notice => "Restaurant deleted."
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  	base_title = "TrueDine"
  	if page_title.empty?
  		base_title
  	else
  		"#{base_title} | #{page_title}"
  	end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
  def calender(date = Date.today,&block)
  	Calender.new(self, date, block).table	
  end

  class Calender < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calender" do
      	header + week_rows
      end		
    end	

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day}.join.html_safe	
      end
    	
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe	
        end	
      end.join.html_safe
    	
    end
    def day_cell(day)
      content_tag :td, view.capture(day,&callback),class: day_classes(day) 	
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_font.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400' rel='stylesheet' type='text/css'>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",  '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "TrueDine Restaurants",'#'%></li>
    </ul>
  </nav>
  <small>
    2013 TrueDine. All Rights Reserved
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container">
      
      <%= link_to "TrueDine", '#', id: "logo" %>
      <%= link_to image_tag("fork-knife-hi.png", alt: "Rails"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right navbold">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <li class="<%= 'active' if current_page?(restaurants_path) %>"><%= link_to "Restaurants",restaurants_path %></li>
          <li class="<%= 'active' if current_page?(works_url) %>"><%= link_to "How it works", works_url %></li>
          <%if user_signed_in?%>
            <%if current_user.has_role? :admin %>
              <li><%= link_to('Admin', users_path) %></li>
            <% end %>
            <% if current_user.has_role? :restaurant %>
               <li><%= link_to('Reservations', '#') %></li>
            <%end%>  
           
          <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <%else%>
          <li><%= link_to "already a member? Sign in",new_user_session_path %></li>
          <li><%= link_to "Sign up",new_user_registration_path  %></li>
          <%end%>
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_searchbar.html.erb
<%=form_tag search_url, method: :get, :class =>'form-search center' do%>
  <%=text_field_tag :query, params[:query] ,{:class=>"input-xxlarge search-query", :placeholder=>"Restaurants,Locations, Cuisines"}%>
     <button type="submit" class="btn">Search</button>
   <%end%>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/_social_buttons.html.erb
<!-- AddThis Smart Layers BEGIN -->
<!-- Go to http://www.addthis.com/get/smart-layers to customize -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-520216e11e5326b0"></script>
<script type="text/javascript">
  addthis.layers({
    'theme' : 'transparent',
    'share' : {
      'position' : 'left',
      'numPreferredServices' : 5
    }, 
    'follow' : {
      'services' : [
        {'service': 'facebook', 'id': 'TrueDine'},
        {'service': 'twitter', 'id': 'TrueDineUganda'}
      ]
    },  
    'whatsnext' : {},  
    'recommended' : {
      'title': 'Recommended for you:'
    } 
  });
</script>
<!-- AddThis Smart Layers END -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%=render 'layouts/shim' %>
  <%=render 'layouts/font' %>
  <%= filepicker_js_include_tag %>

</head>
<body>
<%= render 'layouts/header' %>
<div class='container'>
 <%= render 'layouts/social_buttons' %>
 <%= render 'layouts/messages' %>
 <%= render 'layouts/searchbar' %>

<%= yield %>
<%=render 'layouts/footer' %>
</div>